export {
  MY_NOTIFICATIONS,
  UNREAD_NOTIFICATION_COUNT,
  MARK_NOTIFICATION_READ,
  MARK_ALL_NOTIFICATIONS_READ,
  ARCHIVE_NOTIFICATION,
  SEND_ADMIN_BROADCAST,
  NEW_NOTIFICATION_SUB,
} from "@ctrend/shared/graphql/notifications";
